Repository paritytech/fether, pull requests merged in 2018-12, with the labels that each got.

#279 Add gas estimation to the `postTransaction` RPC
  packages/fether-react/package.json
  packages/fether-react/src/RequireHealthOverlay/RequireHealthOverlay.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/utils/estimateGas.js
  packages/fether-react/src/utils/withHealth.js
  yarn.lock
Labels: A8-looksgood

#286 fix: Fixes #285 sed error on macOS
  packages/fether-electron/scripts/fixElectronBug.sh
  packages/fether-electron/scripts/revertElectronBug.sh
Labels: A8-looksgood

#289 fix: Fixes #248. Add validation warning when user tries to send ETH or a token to the zero account
  packages/fether-react/src/Send/TxForm/TxForm.js
Labels: A8-looksgood

#290 fix: Fixes #251. Show validation error when value to send decimal places exceeds max decimal places of token
  packages/fether-react/src/Send/TxForm/TxForm.js
Labels: A8-looksgood

#284 Support BIP39 recovery and use BIP39 for new accounts (fix #207 #199)
  package.json
  packages/fether-electron/package.json
  packages/fether-react/config-overrides.js
  packages/fether-react/craco.config.js
  packages/fether-react/package.json
  packages/fether-react/public/index.html
  packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
  packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
  packages/fether-react/src/BackupAccount/BackupAccount.js
  packages/fether-react/src/stores/createAccountStore.js
  packages/fether-react/src/stores/createAccountStore.spec.js
  packages/fether-react/src/stores/utils/getParityWordlist.js
  packages/fether-react/src/utils/backupAccount.js
  yarn.lock
Labels: A8-looksgood, A9-buythatmanabeer

#296 fix: Fixes BigNumber error due to incorrect number type
  packages/fether-react/src/Send/TxForm/TxForm.js
Labels: A8-looksgood, M4-core

#304 Select default array from imported list of tokens
  packages/fether-react/src/Whitelist/Whitelist.js
Labels: A8-looksgood

#291 fix: Fixes #244. Concatenate balances to 2 decimal places on account overview page without rounding
  packages/fether-ui/src/TokenCard/TokenCard.js
Labels: A8-looksgood, M7-ui

#315 docs: Add troubleshooting tip suggesting to reload when stuck on white screen
  README.md
Labels: A8-looksgood

#302 Add Max button to send the whole balance
  packages/fether-react/package.json
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/assets/sass/shared/_button.scss
  packages/fether-react/src/assets/sass/shared/_form.scss
  packages/fether-ui/src/Form/Form.js
  yarn.lock
Labels: A8-looksgood

#274 Update @parity/* packages & fix #298
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/utils/estimateGas.js
  packages/fether-react/src/utils/withHealth.js
  yarn.lock
Labels: A8-looksgood
