Repository paritytech/fether, pull requests merged in 2018-11, with the labels that each got.

#227 Don't install node on CI
  .gitlab-ci.yml
Labels: A2-insubstantial

#217 Add chainName to Synced/Syncing health status
  packages/fether-react/src/Health/Health.js
  packages/fether-react/src/utils/withHealth.js
Labels: A8-looksgood

#223 Fix linux icons (electron-builder)
  .gitignore
  packages/fether-electron/build/icons/1024.png
  packages/fether-electron/build/icons/128.png
  packages/fether-electron/build/icons/512.png
  packages/fether-electron/electron-builder.json
Labels: A8-looksgood

#229 Fix slow sync
  packages/fether-react/package.json
  yarn.lock
Labels: A8-looksgood

#230 Fix bug confirmations not working with latest light.js
  packages/fether-react/package.json
  yarn.lock
Labels: A8-looksgood

#236 Update readme with clearer install instructions
  README.md
Labels: A8-looksgood

#237 Update package.json
  packages/fether-electron/package.json
Labels: A8-looksgood

#241 Update @parity/electron dependency (fix #240)
  packages/fether-electron/package.json
  yarn.lock
Labels: A8-looksgood

#216 RequireHealthOverlay: App (require connection) and TxForm & Signer (require sync)
  packages/fether-react/src/App/App.js
  packages/fether-react/src/Health/Health.js
  packages/fether-react/src/Overlay/Overlay.js
  packages/fether-react/src/RequireHealthOverlay/RequireHealthOverlay.js
  packages/fether-react/src/RequireHealthOverlay/index.js
  packages/fether-react/src/Send/Signer/Signer.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/assets/sass/components/_alert-screen.scss
  packages/fether-react/src/assets/sass/layouts/_wrapper.scss
Labels: A0-pleasereview

#256 Bump to version 0.1.1
  package.json
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-ui/package.json
Labels: A8-looksgood

#258 Switch back to Parity Ethereum beta
  packages/fether-electron/package.json
Labels: A8-looksgood

#261 Bump to 0.1.2
  package.json
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-ui/package.json
Labels: A8-looksgood

#263 WithHealth: Wait 2s before showing not synced (fix #262)
  packages/fether-react/src/RequireHealthOverlay/RequireHealthOverlay.js
  packages/fether-react/src/utils/withHealth.js
Labels: A8-looksgood

#255 add tooltip warning when recipient address is the same as sender address
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-ui/src/Form/Field/Field.js
Labels: A8-looksgood

#271 Use arrow instead of close icons
  packages/fether-react/src/Send/Signer/Signer.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Whitelist/Whitelist.js
Labels: A2-insubstantial, A8-looksgood
