Repository paritytech/fether, pull requests merged in 2019-11, with the labels that each got.

#576 fix: CI install node12 for windows
  .gitlab-ci.yml
Labels: A0-pleasereview

#577 chore: bump 0.4.1
  lerna.json
  package.json
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-ui/package.json
Labels: A2-insubstantial

#578 Force at least the Istanbul release
  packages/fether-electron/package.json
Labels: A8-looksgood
