Repository paritytech/fether, pull requests merged in 2019-04, with the labels that each got.

#482 fix: Relates to #466. Update Webcam error messages to refer to Fether FAQ
  packages/fether-react/src/Scanner/Scanner.js
  packages/fether-react/src/assets/sass/shared/_basics.scss
  packages/fether-ui/src/ExternalLink/ExternalLink.js
  packages/fether-ui/src/ExternalLink/index.js
  packages/fether-ui/src/index.js
Labels: A8-looksgood

#487 Use path join to build on Windows
  scripts/fetch-latest-parity.js
Labels: A8-looksgood

#489 Use path.join in fetch-latest-parity.js
  scripts/fetch-latest-parity.js
Labels: A8-looksgood

#488 Use atomiclabs/cryptocurrency-icons/ set of icons
  packages/fether-react/src/assets/tokens/foundation.json
  packages/fether-react/src/assets/tokens/goerli.json
  packages/fether-react/src/assets/tokens/kovan.json
  packages/fether-react/src/assets/tokens/ropsten.json
  scripts/updateTokens/update-tokens-utils.ts
  scripts/updateTokens/update-tokens.ts
Labels: A8-looksgood

#491 refactor: Update craco and remove --react-scripts workaround
  packages/fether-react/craco.config.js
  packages/fether-react/package.json
  yarn.lock
Labels: A8-looksgood

#451 fix: Relates to #124. Security
  package.json
  packages/fether-electron/build/icons/webpack/compile.png
  packages/fether-electron/build/icons/webpack/failure.png
  packages/fether-electron/build/icons/webpack/success.png
  packages/fether-electron/build/icons/webpack/warning.png
  packages/fether-electron/custom.webpack.additions.js
  packages/fether-electron/electron-webpack.json
  packages/fether-electron/package.json
  packages/fether-electron/src/main/app/cli/index.js
  packages/fether-electron/src/main/app/constants/index.js
  packages/fether-electron/src/main/app/menu/template/index.js
  packages/fether-electron/src/main/app/methods/setupGlobals.js
  packages/fether-electron/src/main/app/methods/setupRequestListeners.js
  packages/fether-electron/src/main/app/methods/setupWinListeners.js
  packages/fether-electron/src/main/app/options/config/index.js
  packages/fether-electron/src/main/app/options/index.js
  packages/fether-electron/src/main/app/parityEthereum/index.js
  packages/fether-electron/src/main/app/utils/csp.js
  packages/fether-electron/src/main/app/utils/isTrustedUrlPattern.js
  packages/fether-electron/src/main/app/utils/isTrustedUrlPattern.spec.js
  packages/fether-electron/src/main/app/utils/paths.js
  packages/fether-electron/src/main/index.js
  packages/fether-electron/static/preload.js
  packages/fether-react/package.json
  packages/fether-react/public/index.html
  packages/fether-react/src/App/App.js
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/stores/parityStore.js
  packages/fether-react/src/utils/blockscout.js
  packages/fether-react/src/utils/localForage.js
  packages/fether-react/src/utils/withHealth.js
  scripts/updateTokens/types/TokensJson.ts
  yarn.lock
Labels: A8-looksgood

#498 fix: Fix small bugs after hasty merge
  package.json
  packages/fether-electron/package.json
  packages/fether-electron/src/main/app/cli/index.js
  packages/fether-electron/src/main/app/methods/setupGlobals.js
  packages/fether-electron/static/preload.js
  packages/fether-react/package.json
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-ui/package.json
  yarn.lock
Labels: A0-pleasereview

#492 perf: Bump light.js to use getTxByHash
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-react/src/Send/Sent/Sent.js
  yarn.lock
Labels: A1-onice, A8-looksgood

#479 Prepare for Mainnet launch
  README.md
  packages/fether-electron/src/main/app/constants/index.js
Labels: A8-looksgood, M3-docs

#501 chore: Allow fetching cross-platform parity-ethereum
  .gitlab-ci.yml
  package.json
  scripts/fetch-latest-parity.js
Labels: A0-pleasereview

#499 Bump Fether to v0.4.0
  lerna.json
  package.json
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-ui/package.json
Labels: A8-looksgood

#452 feat: Relates to #402. Internationalisation. Base Support
  package.json
  packages/fether-electron/package.json
  packages/fether-electron/src/main/app/menu/i18n/index.js
  packages/fether-electron/src/main/app/menu/i18n/locales/en.json
  packages/fether-electron/src/main/app/menu/i18n/locales/index.js
  packages/fether-electron/src/main/app/menu/template/index.js
  packages/fether-electron/static/preload.js
  packages/fether-react/package.json
  packages/fether-react/src/Accounts/AccountsList/AccountsList.js
  packages/fether-react/src/Accounts/AccountsList/Feedback/Feedback.js
  packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
  packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
  packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
  packages/fether-react/src/Accounts/CreateAccount/CreateAccount.js
  packages/fether-react/src/App/App.js
  packages/fether-react/src/BackupAccount/BackupAccount.js
  packages/fether-react/src/Health/Health.js
  packages/fether-react/src/Onboarding/Onboarding.js
  packages/fether-react/src/RequireHealthOverlay/HealthModal/HealthModal.js
  packages/fether-react/src/RequireHealthOverlay/RequireHealthOverlay.js
  packages/fether-react/src/Scanner/Scanner.js
  packages/fether-react/src/Send/ScanSignedTx/ScanSignedTx.js
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/Send/SignedTxSummary/SignedTxSummary.js
  packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Send/TxQrCode/TxQrCode.js
  packages/fether-react/src/Send/Unlock/Unlock.js
  packages/fether-react/src/Tokens/Tokens.js
  packages/fether-react/src/Tokens/TokensList/TokenAddress/TokenAddress.js
  packages/fether-react/src/Tokens/TokensList/TokensList.js
  packages/fether-react/src/Whitelist/NewTokenItem/NewTokenItem.js
  packages/fether-react/src/Whitelist/Whitelist.js
  packages/fether-react/src/i18n/index.js
  packages/fether-react/src/i18n/locales/en.json
  packages/fether-react/src/i18n/locales/index.js
  packages/fether-react/src/utils/blockscout.js
  packages/fether-ui/src/AccountCard/AccountCard.js
  packages/fether-ui/src/AccountHeader/AccountHeader.js
  packages/fether-ui/src/ClickToCopy/ClickToCopy.js
  packages/fether-ui/src/Form/InputFile/InputFile.js
  scripts/fetch-latest-parity.js
  yarn.lock
Labels: A8-looksgood

#464 feat: Relates to #402. Internationalisation. German Language Support
  packages/fether-electron/src/main/app/menu/i18n/index.js
  packages/fether-electron/src/main/app/menu/i18n/locales/de.json
  packages/fether-electron/src/main/app/menu/i18n/locales/index.js
  packages/fether-electron/src/main/app/menu/template/index.js
  packages/fether-react/src/i18n/index.js
  packages/fether-react/src/i18n/locales/de.json
  packages/fether-react/src/i18n/locales/index.js
Labels: A8-looksgood

#496 fix: Fixes #494 Drag vs Context menu. Import options page error and colour
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/CreateAccount.js
  packages/fether-react/src/assets/sass/components/_account-import.scss
  packages/fether-react/src/assets/sass/shared/_basics.scss
  packages/fether-react/src/index.sass
  packages/fether-ui/src/Form/InputFile/InputFile.js
Labels: A8-looksgood

#483 feat: Relates to #360. Only allow import from Parity Signer chain account matching current chain. ETC support
  packages/fether-react/package.json
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
  packages/fether-react/src/Health/Health.js
  packages/fether-react/src/Onboarding/termsAndConditions.md
  packages/fether-react/src/Send/SignedTxSummary/SignedTxSummary.js
  packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/assets/img/tokens/classic.svg
  packages/fether-react/src/i18n/locales/de.json
  packages/fether-react/src/i18n/locales/en.json
  packages/fether-react/src/stores/createAccountStore.js
  packages/fether-react/src/stores/createAccountStore.spec.js
  packages/fether-react/src/stores/sendStore.js
  packages/fether-react/src/stores/sendStore.spec.js
  packages/fether-react/src/utils/blockscout.js
  packages/fether-react/src/utils/chain.js
  packages/fether-react/src/utils/testHelpers/mock.js
  packages/fether-react/src/utils/transaction.js
  packages/fether-react/src/utils/withBalance.js
  packages/fether-react/src/utils/withTokens.js
Labels: A8-looksgood
