Repository paritytech/fether, pull requests merged in 2019-03, with the labels that each got.

#460 fix: Fixes #459. Use default role for Edit menu on macOS
  packages/fether-electron/src/main/app/menu/template/index.js
Labels: A8-looksgood, P0-dropeverything

#461 fix: Fix warning since lifecycle method should be componentWillUnmount
  packages/fether-react/src/App/App.js
Labels: A8-looksgood

#463 Use preload script as buffer between main and renderer processes
  packages/fether-electron/electron-webpack.json
  packages/fether-electron/package.json
  packages/fether-electron/src/main/app/options/config/index.js
  packages/fether-electron/src/main/app/options/config/preload.js
  packages/fether-react/package.json
  packages/fether-react/src/stores/parityStore.js
  packages/fether-react/src/utils/withHealth.js
  yarn.lock
Labels: A0-pleasereview

#391 feat: Fixes #390. Show shortened version if account name over 25 chars
  packages/fether-react/src/assets/sass/components/_account.scss
  packages/fether-ui/src/AccountCard/Name/Name.js
Labels: A8-looksgood

#470 Center account header
  packages/fether-react/src/assets/sass/components/_account.scss
Labels: A2-insubstantial, A8-looksgood

#468 feat: Add Reload to taskbar menu in development only
  packages/fether-electron/src/main/app/menu/template/index.js
Labels: A0-pleasereview

#471 Move unessential content to the wiki
  README.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#458 Parity Ethereum bundling
  .gitignore
  LICENSE
  package.json
  packages/fether-electron/package.json
  packages/fether-electron/src/main/app/messages/index.js
  packages/fether-electron/src/main/app/methods/setupParityEthereum.js
  packages/fether-electron/src/main/app/methods/showTrayBalloon.js
  packages/fether-electron/src/main/app/options/config/index.js
  packages/fether-electron/src/main/app/parityEthereum/index.js
  packages/fether-electron/src/main/app/utils/paths.js
  packages/fether-react/package.json
  packages/fether-react/src/Accounts/AccountsList/AccountsList.js
  packages/fether-react/src/App/App.js
  packages/fether-react/src/Health/Health.js
  packages/fether-react/src/RequireHealthOverlay/HealthModal/HealthModal.js
  packages/fether-react/src/RequireParityVersion/RequireParityVersion.js
  packages/fether-react/src/RequireParityVersion/index.js
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Send/Unlock/Unlock.js
  packages/fether-react/src/Whitelist/Whitelist.js
  packages/fether-react/src/stores/sendStore.js
  packages/fether-react/src/stores/sendStore.spec.js
  packages/fether-react/src/utils/withAccount.js
  packages/fether-react/src/utils/withAccountsInfo.js
  packages/fether-react/src/utils/withBalance.js
  packages/fether-react/src/utils/withHealth.js
  packages/fether-react/src/utils/withTokens.js
  scripts/fetch-latest-parity.js
  yarn.lock
Labels: A8-looksgood

#472 fix: correctly set permissions on downloaded binary
  scripts/fetch-latest-parity.js
Labels: A0-pleasereview, A2-insubstantial

#473 Convert the gasPrice to Gwei for Parity Signer transactions
  packages/fether-react/src/utils/transaction.js
Labels: A8-looksgood

#414 refactor: Don't call transactionCountOf$ until needed
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Tokens/TokensList/TokenBalance/TokenBalance.js
  packages/fether-react/src/Tokens/TokensList/TokensList.js
  packages/fether-react/src/index.js
  packages/fether-react/src/utils/withAccount.js
  packages/fether-react/src/utils/withBalance.js
Labels: A8-looksgood

#476 fix: Relates to #474. Fix so Transaction Details shows missing inputs instead of incorrect values
  packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
Labels: A8-looksgood

#478 Make sure long token names don't break the UI
  packages/fether-react/src/assets/sass/components/_header-nav.scss
  packages/fether-react/src/assets/sass/components/_token.scss
Labels: A2-insubstantial, A8-looksgood

#477 Use new token contract's source
  package.json
  packages/fether-react/scripts/updateTokens.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Tokens/TokensList/TokenBalance/TokenBalance.js
  packages/fether-react/src/Tokens/TokensList/TokensList.js
  packages/fether-react/src/Whitelist/NewTokenItem/NewTokenItem.js
  packages/fether-react/src/Whitelist/Whitelist.js
  packages/fether-react/src/assets/img/tokens/default-token-128x128.jpg
  packages/fether-react/src/assets/tokens/foundation.json
  packages/fether-react/src/assets/tokens/kovan.json
  packages/fether-react/src/assets/tokens/ropsten.json
  packages/fether-ui/src/TokenCard/TokenCard.js
  packages/fether-ui/src/assets/img/tokens/token-placeholder-128x128.jpg
  scripts/updateTokens/README.md
  scripts/updateTokens/index.ts
  scripts/updateTokens/tsconfig.json
  scripts/updateTokens/types/CommitStatus.ts
  scripts/updateTokens/types/GitCommit.ts
  scripts/updateTokens/types/Token.ts
  scripts/updateTokens/types/TokensJson.ts
  scripts/updateTokens/update-tokens-utils.ts
  scripts/updateTokens/update-tokens.ts
  yarn.lock
Labels: A8-looksgood
