Repository paritytech/fether, pull requests merged in 2019-01, with the labels that each got.

#328 Merge into yj-focus-formfield - Don't use keycodes
  packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js
  packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
  packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
  packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
  packages/fether-react/src/BackupAccount/BackupAccount.js
  packages/fether-ui/src/Form/Field/Field.js
Labels: A0-pleasereview

#319 feat: Relates to #128. Add feedback button that links to Fether Github new issue
  packages/fether-react/src/Accounts/AccountsList/AccountsList.js
  packages/fether-react/src/Accounts/AccountsList/Feedback/Feedback.js
  packages/fether-react/src/Accounts/AccountsList/Feedback/index.js
  packages/fether-react/src/assets/sass/components/_footer-nav.scss
Labels: A8-looksgood

#307 feat - Fixes #293. Shows tx fee estimate and total tx amount. See issues in commit details
  packages/fether-react/src/Onboarding/Onboarding.js
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
  packages/fether-react/src/Send/TxForm/TxDetails/index.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/assets/sass/components/_form-nav.scss
  packages/fether-react/src/assets/sass/modules/_variables.scss
  packages/fether-react/src/assets/sass/shared/_basics.scss
  packages/fether-react/src/assets/sass/shared/_form.scss
Labels: A8-looksgood

#321 feat: Fixes #308. Change amount font size on Send page to fit in input field
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/assets/sass/shared/_form.scss
Labels: A8-looksgood

#327 fix: Relates to #138. Prevents user from importing account that is already in account list
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-ui/src/AddressShort/AddressShort.js
  packages/fether-ui/src/index.js
  packages/fether-ui/src/utils/addressShort.js
  packages/fether-ui/src/utils/index.js
Labels: A8-looksgood

#339 Switch order from "to" and "amount" fields on Signer screen
  packages/fether-react/src/Send/Signer/Signer.js
  packages/fether-react/src/assets/sass/shared/_form.scss
Labels: A8-looksgood, Q0-trivial

#340 "Transaction Details" viewable any time
  packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
  packages/fether-react/src/Send/TxForm/TxForm.js
Labels: A8-looksgood, M7-ui

#346 Bump version to 0.2.0
  lerna.json
  package.json
  packages/fether-electron/package.json
  packages/fether-react/package.json
  packages/fether-ui/package.json
Labels: A8-looksgood

#351 Accept 11 words legacy recovery phrases for Parity Signer compatibility
  packages/fether-react/src/stores/createAccountStore.js
Labels: A8-looksgood, Q0-trivial

#353 Fix Warning about unique "key" prop
  packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
Labels: A8-looksgood, Q0-trivial

#336 Integrate Parity Signer into Fether
  packages/fether-react/package.json
  packages/fether-react/public/index.html
  packages/fether-react/src/Accounts/AccountsList/AccountsList.js
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
  packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
  packages/fether-react/src/Accounts/CreateAccount/CreateAccount.js
  packages/fether-react/src/BackupAccount/BackupAccount.js
  packages/fether-react/src/Scanner/Scanner.js
  packages/fether-react/src/Scanner/index.js
  packages/fether-react/src/Send/ScanSignedTx/ScanSignedTx.js
  packages/fether-react/src/Send/ScanSignedTx/index.js
  packages/fether-react/src/Send/Send.js
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/Send/SignedTxSummary/SignedTxSummary.js
  packages/fether-react/src/Send/SignedTxSummary/index.js
  packages/fether-react/src/Send/TxForm/TxForm.js
  packages/fether-react/src/Send/TxQrCode/TxQrCode.js
  packages/fether-react/src/Send/TxQrCode/index.js
  packages/fether-react/src/Send/Unlock/Unlock.js
  packages/fether-react/src/Send/Unlock/index.js
  packages/fether-react/src/Tokens/Tokens.js
  packages/fether-react/src/Tokens/TokensList/TokenBalance/TokenBalance.js
  packages/fether-react/src/Whitelist/Whitelist.js
  packages/fether-react/src/assets/sass/components/_account.scss
  packages/fether-react/src/assets/sass/components/_form-nav.scss
  packages/fether-react/src/assets/sass/shared/_box.scss
  packages/fether-react/src/assets/sass/shared/_text.scss
  packages/fether-react/src/stores/createAccountStore.js
  packages/fether-react/src/stores/sendStore.js
  packages/fether-react/src/utils/transaction.js
  packages/fether-react/src/utils/transaction.spec.js
  packages/fether-react/src/utils/withAccount.js
  packages/fether-react/src/utils/withAccountsInfo.js
  packages/fether-react/src/utils/withBalance.js
  packages/fether-react/src/utils/withTokens.js
  packages/fether-ui/babel.config.js
  packages/fether-ui/package.json
  packages/fether-ui/src/AccountCard/AccountCard.js
  packages/fether-ui/src/AccountCard/Avatar/Avatar.js
  packages/fether-ui/src/AccountCard/Avatar/signerIcon.png
  packages/fether-ui/src/AccountCard/Avatar/signerIcon.svg
  packages/fether-ui/src/AccountHeader/AccountHeader.js
  yarn.lock
Labels: A8-looksgood, A9-buythatmanabeer

#370 Change Cancel to Back button. Password field autofocus on Unlock component
  packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js
  packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
  packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
  packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
  packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
  packages/fether-react/src/BackupAccount/BackupAccount.js
  packages/fether-react/src/Send/ScanSignedTx/ScanSignedTx.js
  packages/fether-react/src/Send/TxQrCode/TxQrCode.js
  packages/fether-react/src/Send/Unlock/Unlock.js
  packages/fether-react/src/assets/sass/shared/_button.scss
Labels: A0-pleasereview

#375 CI: add key for the cache
  .gitlab-ci.yml
Labels: A8-looksgood

#356 feat: Relates to #264. SUI-based drop-down menu with Backup Account and Add Tokens
  packages/fether-react/src/Tokens/Tokens.js
  packages/fether-react/src/assets/img/icons/menu.svg
  packages/fether-react/src/assets/sass/components/_header-nav.scss
  packages/fether-react/src/assets/sass/components/_popup.scss
  packages/fether-react/src/assets/sass/components/_token.scss
  packages/fether-react/src/index.sass
  packages/fether-ui/src/MenuPopup/MenuPopup.js
  packages/fether-ui/src/MenuPopup/index.js
  packages/fether-ui/src/index.js
Labels: A8-looksgood

#377 fix: Relates to #324. Show link to Blockscout upon confirmed, not the first confirmation
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/assets/sass/components/_alert-screen.scss
Labels: A8-looksgood

#363 feat: Relates to #337. Part 1 of 2 - Account view - Change header account design
  packages/fether-react/src/Accounts/AccountsList/AccountsList.js
  packages/fether-react/src/assets/sass/components/_account.scss
  packages/fether-react/src/assets/sass/components/_header-nav.scss
  packages/fether-ui/src/AccountCard/AccountCard.js
  packages/fether-ui/src/AccountCard/Name/Name.js
  packages/fether-ui/src/AccountHeader/AccountHeader.js
  packages/fether-ui/src/Header/Header.js
Labels: A8-looksgood

#381 fix: Fix txStatus race condition in sendStore
  packages/fether-react/src/Send/Sent/Sent.js
  packages/fether-react/src/stores/sendStore.js
Labels: A8-looksgood

#385 Fix sync rate not showing
  packages/fether-react/src/utils/withHealth.js
Labels: A8-looksgood

#396 [Merge into luke's taskbar PR] Fix icons
  packages/fether-electron/src/main/app/options/config/index.js
  packages/fether-electron/static/assets/icons/_parity-ethereum-fether-icon.png
  packages/fether-electron/static/assets/icons/parity-ethereum-fether-icon.png
  packages/fether-electron/static/assets/icons/parity-ethereum-fether-icon@2.png
  packages/fether-electron/static/assets/icons/parity-ethereum-fether-icon@3.png
Labels: A0-pleasereview, A2-insubstantial
