Repository paritytech/fether, pull requests merged in 2019-10, with the labels that each got.

#561 fix: Only emit correctly-formed JSONRPC message
  packages/fether-electron/src/main/app/ipcChannel/index.js
  packages/fether-react/src/utils/PostMessageProvider.js
Labels: A0-pleasereview

#563 Add Appimage security warning
  README.md
Labels: A0-pleasereview

#565 Fix unhandled transport errors
  packages/fether-react/src/utils/PostMessageProvider.js
Labels: A8-looksgood

#568 Fix PostMessageProvider unsubscribe
  packages/fether-react/src/utils/PostMessageProvider.js
Labels: A8-looksgood

#569 ci: upgrade to node:12
  .gitlab-ci.yml
Labels: A8-looksgood

#570 chore: do not upload to snap store
  packages/fether-electron/electron-builder.json
Labels: A0-pleasereview, A2-insubstantial
